site_name: Dark Cosmos
site_url: https://darkcosmos.xenosnowfox.com/
copyright: >
  Dark Cosmos ©2024 is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="license noopener noreferrer nofollow">Creative Commons Attribution-ShareAlike 4.0 International <img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="//mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="//mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a>
nav:
  - 'Dark Cosmos': 'index.md'
  - 'Session Notes':
    - 'S01: Lost & Found': 'session-notes/season-one.md'
  - 'Crew':
    - 'Algernon Blue': 'crew/algernon-blue.md'
    - 'Arc Ferris': 'crew/arc-ferris.md'
    - 'Voel Burung': 'crew/voel-burung.md'
    - 'The Coyfish (ship)': 'crew/the-coyfish.md'
  - 'Erilia Sector':
    - 'About the Erilia Sector': 'sector/erilia.md'
    - 'Star Systems of Erilia':
      - 'Bechil Quadrant': 'star-system/bechil-quadrant.md'
      - 'Carroid': 'star-system/caaroid.md'
      - 'Kep': 'star-system/kep.md'
      - 'Leonis Vortex': 'star-system/leonis-vortex.md'
      - 'Pangatis': 'star-system/pangatis.md'
      - 'Solairace': 'star-system/solairace.md'
  - 'Planets':
    - 'Bechil Quadrant':
      - 'Citadel': 'planet/citadel.md'
      - 'The Burrows': 'planet/the-burrows.md'
    - 'Caaroid':
      - 'Poinope': 'planet/poinope.md'
    - 'Leonis Vortex':
      - 'Ix': 'planet/ix.md'
    - 'Pangatis':
      - 'Concordant Archives': 'planet/concordant-archives.md'
    - 'Solairace':
      - 'Ganymede': 'planet/ganymede.md'
  - 'Places of Interest':
    - 'Bechil Quadrant':
      - 'The Caaroid Blockade': 'places-of-interest/the-caaroid-blockade.md'
      - 'The Scrap Field': 'places-of-interest/the-scrap-field.md'
  - 'Factions':
    - 'Concordant Collective':
      - 'The Concordant Collective': 'faction/concordant-collective/the-concordant-collective.md'
      - 'Concordant News Network': 'faction/concordant-collective/concordant-news-network.md'
      - 'Matrons Engineering Guild': 'faction/concordant-collective/matrons-engineering-guild.md'
    - 'Corporate':
      - 'Quasar Cosmetics': 'faction/corporate/quasar-cosmetics.md'
    - 'Criminal':
      - 'Requiem Insurgency': 'faction/criminal/requiem-insurgency.md'
    - 'Weirdness':
      - 'The Reminiscent Sanctuary': 'faction/weird/the-reminiscent-sanctuary.md'
  - 'NPCs':
    - 'Friends':
      - 'Ada Black': 'npc/ada-black.md'
      - 'Alben': 'npc/alben.md'
      - 'Blish': 'npc/blish.md'
      - 'Hicks': 'npc/hicks.md'
      - 'Jackev': 'npc/jackev.md'
      - 'Mav': 'npc/mav.md'
      - 'Triv and Trel': 'npc/triv-and-trel.md'
  - 'Xeno Species':
    - 'Avali': 'xeno/avali.md'
    - 'Kxal': 'xeno/kxal.md'
    - "Tz'ldani": 'xeno/tzldani.md'
    - 'Yuguar': 'xeno/yuguar.md'
markdown_extensions:
  - toc:
      separator: "_"
      permalink: "⌫"
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.keys
plugins:
  - search
  - callouts
theme:
  name: windmill
  # name: dracula
  # name: bootstrap386
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    # - navigation.indexes
    - search.suggest
    - search.share
    - toc.follow
extra_css:
  - stylesheets/extra.css